import type { Metadata } from "next";
import {inter} from "../lib/fonts";
import "./globals.css";
import { Toaster } from "sonner";
import ReactQueryProvider from "@/components/providers/react-query-provider";

export const metadata: Metadata = {
  title: "Crypto Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-[100dvh] p-6 pb-0 flex flex-col`}
      >
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
